### PR TITLE
Support new JavaScript + More robust processing + Update dependencies

### PR DESCRIPTION
**Pull request by aminya**
- Support parsing new JavaScript
- More robust processing by continuing on undefined or unknown errors
- Update dependencies
- Fix the failing tests
- Add GitHub Actions

Successful CI run:
https://github.com/aminya/jsdoc2flow/actions/runs/497438424

### CODE REVIEW

**Comment by aminya** [comment]
@dannysu Hi! I updated this library. I would like to maintain this project. If you are not interested in maintaining it, could you transfer the repo to me?

**Comment by dannysu** [comment]
Not sure how to transfer to you, but happy to. Github says you already have a repo named the same.

Do you have a npmjs.com account?

**Comment by aminya** [comment]
@dannysu Could you try again? I renamed my fork. 

> Do you have a npmjs.com account?

Yes! This is my ID: `@aminya`

**Comment by dannysu** [comment]
Still get the message "aminya already has a repository in the dannysu/jsdoc2flow network". I think maybe because you already have a forked repo?

Added you to npm. Feel free to take over.

**Comment by aminya** [comment]
> Still get the message "aminya already has a repository in the dannysu/jsdoc2flow network". I think maybe because you already have a forked repo?

Hmm, 🤔 I have deleted the fork now. Maybe, you can do it now. 

> Added you to npm. Feel free to take over.

Thanks. I have big plans for the code. I am mostly interested in integrating it to flow-to-ts as I specified in #3.

**Pull request merged**
